# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: b8e6d7ad890d5e3cee3ec902e2fcfad35c48e0c6e893cfa1d4a3bccaed4c5be22e055de55bc720fea5757b29b810b72079049c9f438a0cec7964e54ebf9f1298

test:
  domain_name: example.com 
  secret_key_base: 6a197018ee29affb5080a9ad01e01167dddd00ff16e6cf4bd22b167ac2a5839e52d09f3d732f25628a79821e0fdc9ab381127e7c4dcac9928ca43ad0e31cbcd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
